import Head from 'next/head'
import Image from 'next/image'
import { Roboto } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const roboto = Roboto({ weight: '400', subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Azion NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <a
            href="https://azion.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              src="/azion.svg"
              alt="Azion Logo"
              className={styles.vercelLogo}
              width={100}
              height={24}
              priority
            />
          </a>

        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.flex}>
          <a
            href="https://www.azion.com/en/documentation/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={roboto.className}>
              Docs
            </h2>
            <p className={roboto.className}>
              Find in-depth information abouthow to create powerful things with Azion.
            </p>
          </a>

          <a
            href="https://manager.azion.com/import-an-existing-project"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={roboto.className}>
              Deploy
            </h2>
            <p className={roboto.className}>
              Instantly deploy your Next.js site to a shareable URL with Azion.
            </p>
          </a>

          <a
            href="https://manager.azion.com/build-application/build/choose-template"
            className={styles.card + ' ' + styles.last}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={roboto.className}>
              Templates
            </h2>
            <p className={roboto.className}>
              Find, test, and deploy edge-enabled software that runs anywhere.
            </p>
          </a>

        </div>
      </main>
    </>
  )
}
